### ISSUE TITLE
where can place init code in totaljs ?

### ISSUE THREAD

**Issue by lyquocnam** [totaljs/node-sqlagent#12]
```
// Example: postgre://user:password@127.0.0.1/database
var Agent = require('sqlagent/pg').connect('connetion-string-to-postgresql');
var sql = new Agent();
```
Can i place this code in where on application ?, in model, controller, or any else ?
it call one or each query on model ?

**Comment by petersirka** [comment]
Hi @lyquocnam,
I store SQLAgent initialization into the `definitions/database.js` e.g. <https://github.com/totaljs/helpdesk/blob/master/definitions/database.js>.

**Comment by lyquocnam** [comment]
thanks @petersirka , got it !
