### ISSUE TITLE
Database connect details object - Not accepted anymore

### ISSUE THREAD

**Issue by Aidan-Chey** [totaljs/node-sqlagent#17]
In sqlAgent version '9.8.1' I was able to specify the connection details for the database in the form of an object like so:
~~~~~
{
  host: 'ipAddress'
  ,port: 1111
  ,user: 'username'
  ,password:''
}
~~~~~
However after updating to 9.9.1, pg mode_module is throwing an error, stating that it expects a string for the URL ("TypeError: Parameter "url" must be a string, not object"). Connection details is a string ( 'postgre://user:password@127.0.0.1/database' ) is accepted.

Is this feature still supported? Is it unique to [MySQL database connections](https://github.com/totaljs/node-sqlagent#important)?

**Comment by petersirka** [comment]
Hi @Aidan-Chey, I have fixed it. Please try to download a new version of SQL Agent from NPM `9.9.2`. Give me a feedback.

**Comment by Aidan-Chey** [comment]
Hi @petersirka I can confirm that this issue has been corrected. I can once again use objects to specify connection details. 
Just a heads up I do have an additional (potentially much larger) bug i'm experiencing regarding dynamic database connections. However I didn't get the time to write a comprehensive issue report about it yesterday.
