### ISSUE TITLE
sample required

### ISSUE THREAD

**Issue by hasan3ysf** [totaljs/node-sqlagent#2]
This looks nice Peter, can you provide a complete simple sample for node-sqlagent with totaljs.

thanks

**Comment by petersirka** [comment]
Hi @hasan3ysf,

Create some definition file like this:
https://github.com/petersirka/node-sqlagent#initialization-for-totaljs

And then continue by this example:
https://github.com/petersirka/node-sqlagent#select

That's all.
Thanks.

**Comment by hasan3ysf** [comment]
var sql = DATABASE();
gave me an error!

**Comment by petersirka** [comment]
Which error?

**Comment by petersirka** [comment]
Definition:

``` javascript
require('sqlagent/sqlserver').init('mssql://user:password@127.0.0.1/database');
```

Controller's action:

``` javascript
function json_users() {
    var sql = DB();

    sql.select('users', 'tbl_users').make(function(builder) {
        builder.where('isremoved', false);
        builder.where('isactivated', true);
        builder.take(50);
        builder.sort('datecreated');
        builder.fields('id', 'alias', 'datecreated');
    });

    sql.exec(function(err, response) {
        if (err)
            return self.throw500(err);     
        self.json(response.users);
    });
}
```

**Comment by hasan3ysf** [comment]
What is the wrong thing I'm doing here :(
![1](https://cloud.githubusercontent.com/assets/840673/10563805/a6ddcac6-75a1-11e5-9203-7814f05007b9.png)

**Comment by hasan3ysf** [comment]
another question @petersirka , how shall I enter the password if it contains the "@" for ezample, my password is: 1@c

thanks

**Comment by hasan3ysf** [comment]
I was able to connect to my server using:
require('sqlagent/sqlserver').init({server: 'myServer', database: 'BKMEC_Live', user: 'sa', password: '1@c' });

but could not connect to the local copy of the SQL that is on my PC, what shall I use as server name, I tried all the below, but none of them worked:
"127.0.0.1", "localhost", "scm", "SQLEXPRESS", scm/SQLEXPRESS"

thanks

**Comment by hasan3ysf** [comment]
Hi @petersirka , any idea what could be the mistake in trying to connect to the local server, as in the screenshot attached above.

Thanks

**Comment by petersirka** [comment]
My SQL Server works correctly but I don't have SQL Server Express instance. SQL Server Express has another connection string and I don't know whether the module `mssql` supports SQL Server Express. Try to find on Google: `sql server express network instance`.

Thanks.

**UPDATE:**
https://github.com/patriksimek/node-mssql#quick-example 

``` javascript
var config = {
    user: '...',
    password: '...',
    server: 'localhost', // You can use 'localhost\\instance' to connect to named instance
    database: '...',

    options: {
        encrypt: true // Use this if you're on Windows Azure
    }
}

// Usage in SQL Agent
require('sqlagent/sqlserver').init(config);
```

**Comment by hasan3ysf** [comment]
Thanks @petersirka 
I'm following now this issue: https://github.com/patriksimek/node-mssql/issues/213
