### ISSUE TITLE
Insert returned identity doesn't handle all alphanumeric types

### ISSUE THREAD

**Issue by Aidan-Chey** [totaljs/node-sqlagent#21]
I've come accross an issue with the value being returned by the "insert" function of SQL Agent. The identity being returned does not handle all types of alphanumeric typed strings. 

As my below example shows, I ask for 4 different sorts of alphanumeric "id"s to be added to the "bug_test" database. They all return something however something unexpected happens for "test_4"; it only returns a few digits of the full "id" value.

Through testing (and the example shows this) i've been able to figure out it's to do with the order of number versus alpha characters. If an alpha character is first, the return is treated like a string the returns the entire string. If a numeric character is first, the return is treated as an integer and only returns the numeric characters up-until the first alpha character in the "id".

I'd expect for the situation like "test_4" to return the full "id" column value '54awdawdawlo' rather than the current '54'.

Using:
SQL Agent 9.9.5
pg 6.4.2

Table: `CREATE TABLE bug_test ( id text primary key );`

Endpoint:
```
	function test_root() {
		var self = this;
		var sql = DATABASE();

		sql.primary('id');
		sql.insert( 'test_1', 'bug_test' ).make(
			(builder) => {
				builder.set('id','e541351');
			}
		);

		sql.primary('id');
		sql.insert( 'test_2', 'bug_test' ).make(
			(builder) => {
				builder.set('id','awlodjawlij');
			}
		);

		sql.primary('id');
		sql.insert( 'test_3', 'bug_test' ).make(
			(builder) => {
				builder.set('id',3546848468);
			}
		);

		sql.primary('id');
		sql.insert( 'test_4', 'bug_test' ).make(
			(builder) => {
				builder.set('id','54awdawdawlo');
			}
		);

		sql.exec(
			(err,response) => {
				self.plain(response);
				/*
					{
					    "test_1": {
					        "identity": "e541351"
					    },
					    "test_2": {
					        "identity": "awlodjawlij"
					    },
					    "test_3": {
					        "identity": 3546848468
					    },
					    "test_4": {
					        "identity": 54
					    }
					}
				*/
			}
		);
	}
```

**Comment by Aidan-Chey** [comment]
Upon looking at pg.js in the sqlagent node_module, my guess would be the issue is at line #1704 where the identity is for some reason (i'm not sure of the purpose of the section of code) being parsed to see if it's an integer.

Javascript's parseInt() seems to return the first integers of a alphanumeric string.
`parseInt('54awdawda') == 54`
So because it didn't actually return NaN, this (54 in this case) is overriding the full identity on line #1709.

**Comment by Aidan-Chey** [comment]
I'd recommend changing the code to something like this:
`
			var tmp = parseInt(rows[0].identity);
			if (isNaN(tmp)) {
				self.id = rows[0].identity;
			} else {
				self.id = tmp;
				rows[0].identity = tmp;
			}`

**Comment by Aidan-Chey** [comment]
Accidentally closed issue...

I've tried re-writing the section of code, but it has made the whole section redundant. eg the section is reduced to: `self.id = rows[0].identity;`

Moving the 'parseInt' into the parameter of the 'isNaN' in the 'if' makes the 'tmp' variable redundant and because the identity is no longer being changed, don't need to reassign it in the 'else'. Now both the result of the 'if' and the 'else' look exactly the same.

Changing the 'if' block to the single line `self.id = rows[0].identity;` does fix the issue, although i'm not sure what it breaks (if anything)...

**Comment by petersirka** [comment]
I'll look into it today/tomorrow.

**Comment by petersirka** [comment]
Hi, can you test it? Test new beta version: `npm install sqlagent@beta`

**Comment by Aidan-Chey** [comment]
Hi Peter,
The beta version is causing an error on every single one of the inserts I have in my example code. 

```
2017-10-02 10:25:54: TypeError: REG_NUMBER.tests is not a function
    at Object.Agent.$bind (project_address/node_modules/sqlagent/pg.js:1707:47)
```

**Comment by petersirka** [comment]
Ohhh my god! I have fixed it. 100x sorry

**Comment by Aidan-Chey** [comment]
Awesome, can confirm that the 'test_4' is returning the entire identity.
I'd consider this issue fixed.

**Comment by petersirka** [comment]
Great, I'm going to publish it to NPM as stable version.

**Comment by petersirka** [comment]
OK, published. Thank you for the report.
