### ISSUE TITLE
Wrong count when using listing and group

### ISSUE THREAD

**Issue by nhannv** [totaljs/node-sqlagent#29]
I'm using listing with builder.join and builder.group, the result responses with wrong count value:
```
sql.listing('stories', 'tbl_story').make(function(builder){
            builder.join('tbl_chapter', 'tbl_story.id=tbl_chapter.storyid');
            builder.group('tbl_story.id');
            builder.sort('createdat', true);
            builder.fields('tbl_story.*','!count(tbl_story.id) as chapters');            
            builder.page(options.page, options.limit);
});
```
I have 3 stories and only the first one has 2 chapters, others don't have any chapters. Then the result responses as (page=1, limit=1):
```
{
    "count": 2,
    "items": {
        ...,
        "chapters": 2
    },
    "page": 1,
    "limit": 1,
    "pages": 2
}
```
When I set page=3, limit=1:
```
{
    "count": 2,
    "items": {
        ...,
        "chapters": 1
    },
    "page": 3,
    "limit": 1,
    "pages": 2
}
```

**Comment by petersirka** [comment]
I'll check it.

**Comment by nhannv** [comment]
I see in this line:
[https://github.com/totaljs/node-sqlagent/blob/master/mysql.js#L1194](url)
It SELECT COUNT(*) at the first query so mysql understand that is the count of each group. Any solution or workaround to use listing with GROUP and COUNT each group as well as return right COUNT of total?

**Comment by petersirka** [comment]
Sorry for big delay. I have fixed it. Please try to download latest beta version `$ npm install sqlagent@beta` and give me a feedback.
