### ISSUE TITLE
Error on second query

### ISSUE THREAD

**Issue by qoole** [totaljs/node-sqlagent#30]
I'm using SQLAgent/sqlserver in a total.js project the first SQL query works as expected but on the second SQL query I get the following error:

"Global connection already exists. Call sql.close() first."

https://stackoverflow.com/questions/44744946/node-js-global-connection-already-exists-call-sql-close-first suggests this would be down to the lack of connection pool being used?

**Comment by qoole** [comment]
I'm in a rush, I can't do a PR but here are some screenshots of alterations that seem to work:

![image](https://user-images.githubusercontent.com/2862661/38299007-da647962-37f0-11e8-8f72-cb0b6042073b.png)

![image](https://user-images.githubusercontent.com/2862661/38298986-cd51509c-37f0-11e8-90dc-025759ac30c8.png)

**Comment by petersirka** [comment]
I'll try to solve it this week.

**Comment by petersirka** [comment]
Sorry for big delay.
I have fixed it. Please try to download latest beta version `$ npm install sqlagent@beta` and give me a feedback.

**Comment by qoole** [comment]
Apologies for the delay here, didn't get a notification on Github.
Seems to be fixed!
Thank you!
