### ISSUE TITLE
Builder doing incorrect column name encapsulation (PostgreSQL)

### ISSUE THREAD

**Issue by Aidan-Chey** [totaljs/node-sqlagent#32]
I'm using SQLAgent (11.0.4) with Sails.js (0.12.14) (irrelevant) to connect to many PostgreSQL (9.5) databases.

I've been finding that when I try to do more advanced SQL the builder tries to encapsulate the wrong part of the column name in double quotes. This causes the database to return an error cause it is being lead to look for a column that I didn't ask for and that dosn't exist in the table.

This issue is avoidable by not using the provided builder helper functions (such as ``builder.where`` and ``builder.fields``) and only using ``server_conntect.query`` and ``builder.sql`` because these don't seem to use the auto-encapsulation system.

The specific problem comes about when I add type casting to the column name like so ``table."column"::type``; this results in the encapsulation system outputing something like this ``table."column::type"``, which makes postgres look for a column named ``column::type``.

Here are some examples on how the query would be built:
```
//Successful
server_connection.sql.select( 'query1', 'tableName').make( builder => {
    builder.fields('CAST ( tableName."columnName" AS INTEGER )');
    builder.where('CAST ( tableName."columnName" AS INTEGER )', 42);
    builder.limit(10);
} );

//Failing
server_connection.sql.select( 'query2', 'tableName').make( builder => {
    builder.fields('tableName."columnName"::integer');
    builder.where('tableName."columnName"::integer', 42);
    builder.limit(10);
} );

//Successful
server_connection.sql.query( 'query3', 'SELECT tableName."columnName"::type FROM tableName').make( builder => {
    builder.sql('tableName."columnName"::type = 42');
    builder.limit(10);
} );
```

To me it looks like the encapsulation code is setup to assume the final part of the column declaration is the column name. Having "::type" to cast the column's value is valid postgres. So perhaps adding an exception that looks for the position of a double colon as the end of the column name.

This is somewhat low priority IMO as the more SQL standard ``CAST ( 'column' AS TYPE )`` can still be used. Although I do wonder why "AS TYPE )" isn't included in the encapsulation...

**Comment by petersirka** [comment]
Hi @Aidan-Chey,
it's a bit complicated with SQL Agent, but it's possible to use:

```javascript
server_connection.sql.select( 'query2', 'tableName').make( builder => {
    builder.schema('tableName');
    builder.fields('columnName --> integer');
    builder.where('columnName --> integer', 42);
    builder.limit(10);
});
```
It's because of casting in another DB engines. Please try it and let me know.

**Comment by Aidan-Chey** [comment]
Oh, i hadn't noticed that option in the readme I see you have it [here for fields](https://github.com/totaljs/node-sqlagent#builderfields). I still have much to learn about SQLAgent.

Adding the type casting for the where function produces some "interesting" results. It dosn't work, it puts things in strange places in the clause. The example you suggested outputs a where clause like this ``tableName."columnName"::int as "columnName"=42`` so for some reason it's added aliasing to the column.

I see the fields function behaves in much the same way, which is unnecessary; ``tableName."columnName"::int as "columnName"`` is the same as ``tableName."columnName"::int``. Looking at the ReadMe, I can see an option to add aliasing by including an `` as alias`` to the column name; so I tried that and the results got even stranger in both the fields and where function, when combined with the type casting. (I won't bother showing example with attempting to alias the where clause as that shouldn't be possible/needed)
```javascript
server_connection.sql.select( 'query2', 'tableName').make( builder => {
    builder.schema('tableName');
    builder.fields('columnName --> integer as "columnAlias"');
    builder.where('columnName --> integer', 42);
    builder.limit(10);
});

//Output Fields
_fields: 'tableName."columnName"integer as "columnAlias" as "columnName"'
//Output Where
builder: [ 'tableName."columnName"::int  as "columnName"=42' ]
```

**Comment by petersirka** [comment]
I have fixed it. Please try to download latest beta version `$ npm install sqlagent@beta` and give me a feedback.

**Comment by Aidan-Chey** [comment]
Dosn't seem to have done much for the original issue (I don't think you were aiming for that). 
However it does seem to have made a marked improvement to the alternative solution you were suggesting; a test like the one above outputs a much better result in fields and where clauses:
```javascript
server_connection.sql.select( 'query2', 'tableName').make( builder => {
    builder.schema('tableName');
    builder.fields('columnName --> integer as "columnAlias"');
    builder.where('columnName --> integer', 42);
    builder.limit(10);
});

//Output Fields
_fields: 'tableName."columnName"::int as "columnAlias"'
//Output Where
builder: [ 'tableName."columnName"::int=42' ]
```

I havn't tested anything other than an integer though so I don't know if that will be an issue. 
Great work @petersirka !
