### ISSUE TITLE
$text operator

### ISSUE THREAD

**Issue by dacrhu** [totaljs/node-sqlagent#36]
Hi,

can you provide the $text operator to MongoDB find method?
That would be useful to text search.

Reference: https://docs.mongodb.com/manual/text-search/

Thank you,
David

**Comment by molda** [comment]
Hi, i can't test it right now, but doesn't the bellow code work already?

    builder.where('$text', { $search: "some text" });

Note that it requires text index on the queried collection.

**Comment by dacrhu** [comment]
Thank you, working fine!
