### ISSUE TITLE
Compound key

### ISSUE THREAD

**Issue by arcanosam** [totaljs/node-sqlagent#4]
Hi! 

There is support to compound key for PostgreSQL?

thanks and congratulations for your work

**Comment by petersirka** [comment]
Hi @arcanosam,
many thanks. Can you write me some SQL query for explanation?

Thx.

**Comment by arcanosam** [comment]
this link http://stackoverflow.com/a/1110364
helps?

**Comment by arcanosam** [comment]
I found this link too: http://weblogs.sqlteam.com/jeffs/archive/2007/08/23/composite_primary_keys.aspx

there is an example

**Comment by petersirka** [comment]
I understand but you can execute SQL with create via `sql.query('CREATE ...')` or did you mean something else? SQL Agent is for classic CRUD operations.

**Comment by arcanosam** [comment]
I got it now... I could do that with raw SQL

I was thinking that could exist some special syntax for defining and querying without using raw SQL.

thanks!

**Comment by petersirka** [comment]
I understand but for better creating tables I don't have any plans.
Documentation describes all functionality for inserting, updating, selecting and deleting.

Thanks!

**Comment by arcanosam** [comment]
when I asked I wasn't thinking right for sure.

No problem, that's functionalities it's enough for me :)

I appreciate your attention
