### ISSUE TITLE
sqlagent error (in some cases)

### ISSUE THREAD

**Issue by werebeaver** [totaljs/node-sqlagent#42]
Hi!
The following problem was detected.

If the total.оs configuration file (config) contains a connection string to mssql like this: 
mssql : mssql://sa:password@develop.net:61000/Database

The following error is observed in the module "TypeError: The "config.options.port" property must be of type number." (file sqlserver.js line 1832)
It is solved with:
                       change
self.options.port = options.port;
                           to 
self.options.port = Number(options.port);

Maybe, there is another way :)

P.S. sqlagent v 12.0.8

**Comment by petersirka** [comment]
Hi @werebeaver,
I have fixed parsing of port. Can you check it? I don't have any instance of SQL Server.

```bash
$ npm install sqlagent
```

**Comment by werebeaver** [comment]
Hi @petersirka!
Everything works great.
Thanks!
