### ISSUE TITLE
Bug with sort

### ISSUE THREAD

**Issue by werebeaver** [totaljs/node-sqlagent#43]
Hi, @petersirka!

I caught a little bug.

In my database there are fields with names: "REPLACEPOST_DESCR", "ddevel_descr", "doctype_descr" and similar ...

The sqlserver.js module on line 244 contains the code
    if (lowered.lastIndexOf ('desc')! == -1 || lowered.lastIndexOf ('asc')! == -1)
which makes the condition true.

As a result, sorting does not work.

sqlagent version 12.0.9-1

Thanks!

**Comment by petersirka** [comment]
Fixed. Just update SQL Agent from NPM.

**Comment by werebeaver** [comment]
Thanks! 
Everything works fine now!
