### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by sowmya369** [totaljs/node-sqlagent#45]
![image](https://user-images.githubusercontent.com/56824715/103542557-2027ca80-4ec3-11eb-9f4e-a43583c0d9d5.png)

**Comment by molda** [comment]
The readme doesn't say anything about `npm install sqlagent/mongodb`

Use `npm install sqlagent` followed by `npm install mongodb`

Also this package haven't been updated in a year. You may want to check https://github.com/totaljs/dbms which is almost identical and regularly maintained.
