### ISSUE TITLE
mssql agent implementation

### ISSUE THREAD

**Issue by andriy-tsvikla** [totaljs/node-sqlagent#47]
Additional information.
I am trying to use flow 10 with totaljs 4 to build simple request - load data from mssql - return response flow.

i am using this as part of my database.js in definitions folder
`var mssqlAgent = require('sqlagent/sqlserver');
var sql = mssqlAgent.connect('connectionString');
`
This is part of Agent.connect defined in your code
`
Agent.connect = function(conn, callback) {
	callback && callback(null);
	var id = (Math.random() * 1000000) >> 0;
	return function(error) {
		return new Agent(conn, error, id);
	};
};
`
as result sql have none of Agent.prototype functions.

and if i use it as 
`
var mssqlAgent = require('sqlagent/sqlserver');
var AgentConstructor = mssqlAgent.connect('connectionString');
var sql = new AgentConstructor();
`
i get this as object 
`
{
  '$conn': 542514,
  isErrorBuilder: true,
  errors: undefined,
  options:'connection',
  db: null,
  command: [],
  done: null,
  last: null,
  id: null,
  '$id': null,
  isCanceled: false,
  index: 0,
  isPut: false,
  skipCount: 0,
  skips: {},
  '$fast': false,
  results: {},
  builders: {},
  '$events': {}
}
`
And no .select .exec etc functions. What am i doing wrong?
Thanks.

**Comment by andriy-tsvikla** [comment]
Maybe this will be helpful to someone.
Used this approach
In definitions/database.js
```

const databases = {};
var mssqlAgent = require('sqlagent/sqlserver');
var agentInstanceConstructor = mssqlAgent.connect('HardcodedConnectionStringValue');
var agentInstance = new agentInstanceConstructor();


//here i was able to run .select and receive result
agentInstance.select('GROUP', '[GROUP]').make(function(builder) {
    builder.fields('[GROUPID]', '[GROUPNAME]');
});

agentInstance.exec(function(err, response) {

    if(err){
        console.log('err');
        console.log(err);
	}
	else {
        console.log('response');
        console.log(response.GROUP);
	}
});

databases.ov = agentInstance;
F.database = function(name) {
    // returns SQL Agent instance
    return databases[name]();
};
```
because i used string values for conn  parameter of connect function
i had to comment part of code in sqlagent/sqlserver.js
https://github.com/totaljs/node-sqlagent/blob/1724ff5dbd5a7d08629be6a7355d1f7b68339f57/sqlserver.js#L1825
because my value was string and it was not parsed correctly. 
Please let me know if there is better way to do this. 
Thanks

**Comment by petersirka** [comment]
Hi @andriy-tsvikla, please make a pull request and we will approve it. Thank you a lot!

**Comment by andriy-tsvikla** [comment]
@petersirka i still cant access select from flow action when i try to access it like 
```
var sql = DATABASE('ov');
sql.select('GROUP', '[GROUP]').make(function(builder) {
    builder.fields('[GROUPID]', '[GROUPNAME]');
});
sql.exec(function(err, response) {
    if(err){
		$.invalid(err);
	}
	else {
		$.success(response.products);
	}
});
```

**Comment by andriy-tsvikla** [comment]
Cant access database from flow component like in example, changed approach
