### ISSUE TITLE
Shows Error When i place order.

### ISSUE THREAD

**Issue by chiragkanjariya** [totaljs/node-sqlagent#5]
it throws error " **The field "order: column "reference" of relation "tbl_order_" does not exist" is required.**" when i place order (http://127.0.0.1:8000/checkout/)

**Comment by petersirka** [comment]
Hi @chiragkanjariya, did you use PG backup for Eshop+CMS?

**Comment by chiragkanjariya** [comment]
i've try to extract "postgresql.tar" but its show damage file.

**Comment by petersirka** [comment]
@chiragkanjariya mhh, I'll fix it.

**Comment by chiragkanjariya** [comment]
ok thanks!

**Comment by petersirka** [comment]
I have looked into it and everything is OK. The screenshot below is from restored `postgresql.tar`.

![image](https://cloud.githubusercontent.com/assets/2414252/17675038/39958448-6328-11e6-9f32-bcd1b71c7aab.png)

BTW: I have created PG script:
https://github.com/totaljs/eshop-cms/blob/master/backup/postgresql.sql
