### ISSUE TITLE
Error on sqlserver.js

### ISSUE THREAD

**Issue by ozgencetinkaya** [totaljs/node-sqlagent#7]
Hi Peter,

I guess, there is a parameter mismatch on the `SqlBuilder` function of `sqlserver.js`.

The variable referenced in the code as `agent` but defined as `aget` in the parameter list. 

``` javascript
function SqlBuilder(skip, take, aget) {
    this.agent = agent;
    this.builder = [];
    this._order = null;
    this._skip = skip >= 0 ? skip : 0;
    this._take = take >= 0 ? take : 0;
    this._set = null;
    this._define;
    this._fn;
    this._join;
    this._fields;
    this._schema;
    this._primary;
    this._group;
    this._having;
    this._is = false;
    this.hasOperator = false;
}
```

Regards,
Ozgen

**Comment by petersirka** [comment]
Hi,
many thanks! This is my big mistake. I don't use MS SQL Server :-( so therefore there was the bug. I have fixed it.

Thank you!
